spring.application.name=sistema-universidade

spring.datasource.url=jdbc:postgresql://localhost:5433/universidade
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8082
spring.thymeleaf.cache=false
